<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
/** @var \Kadoco\PreOrder\Model\IsProductPreOrder $isProductPreOrderViewModel */
$isProductPreOrderViewModel = $block->getData('IsProductPreOrder');
?>
<?php $_product = $block->getProduct(); ?>
<?php
$isProductPreOrder = $isProductPreOrderViewModel->execute($_product);
?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($isProductPreOrder): ?>
    <?php $buttonTitle = __('Pre-order'); ?>
    <style>
        .product-info-stock-sku{ visibility:hidden !important; }
    </style>
<?php endif; ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart qty-incrementor">
    <?php if ($isProductPreOrder): ?>
        <?php $preOrderDate = $isProductPreOrderViewModel->getPreOrderDate($_product);?>
        <?php if (!$preOrderDate): ?>
            <div class="product-pre-order-text">
                <?=__('Pre order the item')?>
            </div>
        <?php else: ?>
            <div class="product-pre-order-text">
                <?=__('Estimated arrival:')?> <?=$preOrderDate?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
    <div class="fieldset add-to-cart-and-qty-incrementer">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       inputmode="numeric"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart <?=$isProductPreOrderViewModel->getPreOrderClass($_product)?>"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>

</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
